apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo-namespace
spec:
  containers:
  - name: demo-container
    image: busybox
    command:
      - "sh"
      - "-c"
      - "env && cat /etc/config/APP_BANNER && sleep 3600"
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_COLOR
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_MODE
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: my-config
